section: screens
	CC-Workstation:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none
		switchCornerSize = 0
	CC-MBP2024.local:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		preserveFocus = false
		switchCorners = none
		switchCornerSize = 0
end

section: aliases
end

section: links
	CC-Workstation:
	CC-MBP2024.local:
end

section: options
	relativeMouseMoves = false
	screenSaverSync = true
	win32KeepForeground = false
	clipboardSharing = true
	clipboardSharingSize = 100000000
	switchDelay = 250
	switchCorners = none
	switchCornerSize = 0
	keystroke(alt+super+Right) = switchKeyboardToScreen(CC-Workstation)
	keystroke(alt+super+Left) = switchKeyboardToScreen(CC-MBP2024.local)
	keystroke(alt+super+Down) = followMouseForKeyboard
end
